config/routes.rb
#
Rails.application.routes.draw do
  # redirects to the appropriate lang
  get '', to: 'frontend#redirect_lang'

  # Start localized routes
  scope '/:locale', locale: /#{Ecommerce.find(ENV['ECOMMERCE_ID']).locales.join('|')}/ do
    # devise
    devise_for :accounts, skip: :registrations, controllers: {
      sessions: 'accounts/sessions',
      passwords: 'accounts/passwords'
    }, path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'password'
      # , confirmation: 'verification',
      # registration: 'register', edit: 'edit'
    }
    devise_scope :account do
      # devise registration
      resource :account_registration, only: [:new], path: "accounts", path_names: {new: "register"}, controller: 'accounts/registrations'
      post "/accounts", controller: "accounts/registrations", action: :create_base, as: :account_registration
      get "/accounts/register/sign_up_vat", controller: "accounts/registrations", action: :new_vat, as: :new_vat_account_registration
      post "/accounts/register_vat", controller: "accounts/registrations", action: :create_vat, as: :vat_account_registration

      resource :account, only: [:edit, :update] do
        get :edit_vat
        get :edit_password
        match :update_vat, via: [:put, :patch]
        match :update_password, via: [:put, :patch]
      end
      # get "/accounts/edit", controller: "accounts", action: :edit, as: :edit_account
      # match "/accounts", controller: "accounts", action: :update, as: :account, via: [:put, :patch]
    end

    # additional devise custom routes
    # namespace :accounts, as: "account", module: nil do
    #   namespace :register, as: "registration", module: "accounts/registrations" do
    #     # get "/accounts/register/sign_up_vat", action: :new_vat, as: :new_vat_account_registration
    #     resource :billing_address, only: [:new, :edit, :update]
    #   end
    # end

    # end devise


    namespace :accounts do
      get :dashboard

      resources :orders, only: [:index, :show] do
        member do
          match :cancel, via: [:put, :patch]
          get :payment
          post :payment, action: :update_payment, as: "update_payment"
        end
      end

      resources :shipping_addresses, except: [:show] do
        match :set_as_default, on: :member, via: [:patch, :put]
      end
    end


    scope module: 'frontend' do
      root to: 'pages#index'
      resources :pages, only: [:show]

      resources :categories, only: [:index, :show]
      resources :products, only: [:show] do
        collection do
          get :price_calc
        end
      end

      # cities and provinces routes
      namespace :addresses do
        # get ":country_id/provinces", action: "provinces", as: :provinces
        get ":province_name/cities", action: "cities", as: :cities
        get ":province_name/:city_name/suggest-cap", action: "suggest_cap", as: :suggest_cap
      end

      namespace :cart do
        root action: :show, as: :show
        post 'add_product/:product_id', action: :add_product, as: :add_product
        delete 'remove_item/:item_id', action: :remove_item, as: :remove_item
        # adds more products via get url
        get 'add_products/:product_ids', action: :add_products_from_url, as: :add_products
        # updates the cart quantities and starts the checkout process
        match '', action: :update, as: :update, via: [:patch, :put]

        # devise registraion and login from the cart
        devise_scope :account do
          namespace :sessions do
            post :create
          end
          namespace :registrations do
            get  :login_or_register
            get  :login_or_register_vat
            post :create_customer
            post :create_vat_account
          end
        end

        # ship address
        get :missing_details
        match :fill_details, via: [:put, :patch]

        get :change_shipping
        post :update_shipping

        get :confirm
        match :make_order, via: [:get, :post]  # final update action that will update the shipping/payment or generate the order
                                               # the GET method is mapped too to correctly intercept the "go back" buttons, a GET request shoul be redirected to the :confirm action
      end

      # path for posting contact forms
      namespace :contacts do
        # post :standard
        post :dynamic, :newsletter
      end

      scope module: "payments" do
        # /en/paga/81/ORD-4973/91.21
        get "paga/:payment_id/:custom_id/:total", action: :external_payment, constraints: {total: /\d+\.\d{2}/}
      end

    end

    # localized error pages
    get '*path', to: 'exceptions#not_found'
  end
  # end localized routes


  # non localized error pages
  get '*path', to: 'exceptions#not_found'
  # Rails expects the error pages to be served from /<error code>.
  match '400', to: 'exceptions#not_found', via: :all
  # error 500 is managed by the file in the public folder, a server error should render a static page!

end

app/controllers/accounts/orders_controller.rb
class Accounts::OrdersController < AccountsController

  add_breadcrumb I18n.t("order_list"), :accounts_orders_path
        

  def index
    # show all account's orders, even if they have been cancelled
    @orders = @current_account.orders.order({created_at: :desc})
    @account_action = "orders"
  end


  def show
    # show all account's orders, even if they have been cancelled
    @order = @current_account.orders.find( params[:id] )
    @account_action = "orders"
    add_breadcrumb "#{t('order_number')} #{@order.custom_id}"
  end


  def cancel
    # only the current_account's active orders can be cancelled
    @order = @current_account.orders.active.find( params[:id] )
    @order.update(cancel_params)
    redirect_to accounts_order_path(@order)
  end



  def payment
    # only the current_account's active orders can be paid
    @order = @current_account.orders.active.find( params[:id] )
    @account_action = "orders"
    @payments = @current_ecommerce.payments.publics.ordered
    add_breadcrumb "#{t('payment')} #{@order.custom_id}"
  end


  def update_payment
    @order = @current_account.orders.active.find( params[:id] )
    @order.update( params[:order].permit(:payment_id) )
    redirect_to action: "payment"
  end



  private

    def cancel_params
      params.require(:order).permit(:reason, :status_note)
    end

end

app/controllers/accounts/passwords_controller.rb
#
class Accounts::PasswordsController < Devise::PasswordsController
  add_breadcrumb I18n.t('retrieve_password')

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  def update
    # devise doesn't check if the password is blank...
    return redirect_to :back if resource_params[:password].blank?
    super
  end

  protected

  #
  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/accounts/registrations_controller.rb
#
class Accounts::RegistrationsController < Devise::RegistrationsController
  include AccountRegistrable
  add_breadcrumb I18n.t('register')

  # this action adds additional custom parameter and then calls the devise's
  # default create
  def create_base
    @additional_resource_params = {
      role: 'basic_user',
      ecommerce_id: @current_ecommerce.id,
      parent_id: EcommerceConfig.store_id
    }
    @failure_view = 'new'
    configure_permitted_parameters
    create_account
  end

  # #
  # def new_vat
  #   build_resource({})
  #   yield resource if block_given?
  #   respond_with resource
  # end

  # #
  # def create_vat
  #   @additional_resource_params = {
  #     role: 'vat_customer',
  #     ecommerce_id: @current_ecommerce.id,
  #     parent_id: EcommerceConfig.store_id
  #   }
  #   @failure_view = 'new_vat'
  #   configure_permitted_parameters
  #   create_account
  # end
end

app/controllers/accounts/sessions_controller.rb
#
class Accounts::SessionsController < Devise::SessionsController
  add_breadcrumb I18n.t('login')
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    # overrides the message with the now options if the request is javascript,
    # to prevent a peristent logout message
    set_flash_message! :notice, :signed_out, { now: true } if signed_out
    yield if block_given?
    respond_to_on_destroy
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    accounts_dashboard_path
  end
end

app/controllers/accounts/shipping_addresses_controller.rb
#
class Accounts::ShippingAddressesController < AccountsController
  before_action :set_account_action
  add_breadcrumb I18n.t('shipping_addresses'), :accounts_shipping_addresses_path

  #
  def index
    @addresses = @current_account.shipping_addresses
  end

  #
  def new
    add_breadcrumb t('new_shipping_address')
    @address = @current_account.shipping_addresses.new
    render 'form'
  end

  #
  def create
    @address = @current_account.shipping_addresses.new(address_params)
    if @address.save
      flash[:shipping_address_success] = t('shipping_address_saved')
      redirect_to edit_accounts_shipping_address_path(id: @address)
    else
      add_breadcrumb t('new_shipping_address')
      render 'form'
    end
  end

  #
  def edit
    @address = @current_account.shipping_addresses.find(params[:id])
    add_breadcrumb t('edit_shipping_address'), edit_accounts_shipping_address_path(id: @address)
    render 'form'
  end

  #
  def update
    @address = @current_account.shipping_addresses.find(params[:id])
    flash.now[:shipping_address_success] = t('shipping_address_saved') if @address.update(address_params)

    render 'form'
  end

  #
  def set_as_default
    @address = @current_account.shipping_addresses.find(params[:id])
    @address.set_as_default!

    redirect_to action: :index
  end

  #
  def destroy
    @address = @current_account.shipping_addresses.find(params[:id])
    @address.destroy
    redirect_to action: :index
  end

  private

  #
  def set_account_action
    @account_action = 'shipping_addresses'
  end

  #
  def address_params
    params.require(:shipping_address).permit(
      %i[name address address_2 country province city cap telephone note
         telephone_prefix]
    )
  end
end

app/controllers/accounts_controller.rb
#
class AccountsController < FrontendController
  before_action :authenticate_account!, :load_account_vars
  add_breadcrumb I18n.t('home'), :root_path
  add_breadcrumb I18n.t('my_account'), :accounts_dashboard_path

  #
  def dashboard
    @account_action = 'dashboard'
    @latest_orders = @account_orders.limit(3)
  end

  # basic edit action
  def edit
    add_breadcrumb t('edit_data'), edit_account_path
    @account_action = 'edit'
  end

  # edit a vat account (this is also used to pass the user from a cliente to a
  # vat account)
  def edit_vat
    add_breadcrumb t('edit_data'), edit_vat_account_path
    @account_action = 'edit'
  end

  #
  def update
    @account_action = 'edit'
    @current_account.role = 'cliente'
    flash.now[:account_success] = t('account_saved') if @current_account.update(account_permitted_params)

    render 'edit'
  end

  #
  def update_vat
    @account_action = 'edit'
    @current_account.role = 'vat_customer'
    flash.now[:account_success] = t('account_saved') if @current_account.update(account_permitted_params)

    render 'edit_vat'
  end

  #
  def edit_password
    add_breadcrumb t('change_password'), edit_password_account_path
    @account_action = 'edit_password'
  end

  #
  def update_password
    @account_action = 'edit_password'

    if @current_account.update_with_password(account_password_permitted_params)
      # if the account password is updated, the user is automatically logged out
      # and the edit action won't be reached but if the password passed is
      # blank, the account won't be updated and he will see the edit form again
      return redirect_to edit_password_account_path
    end

    render 'edit_password'
  end

  private

  #
  def load_account_vars
    # load the orders made by the current account on the ecommerces managed by
    # this application
    @account_orders = @current_account.orders.order(created_at: :desc)
  end

  #
  def account_permitted_params
    if @current_account.vat_customer?
      params.require(:account).permit(
        %i[name surname corporate_name piva cfis telephone_prefix telephone
           phone_prefix phone address address_2 country province city cap]
      )
    else
      params.require(:account).permit(
        %i[name surname cfis address address_2 country province city cap
           telephone phone telephone_prefix phone_prefix birthday sex]
      )
    end
  end

  #
  def account_password_permitted_params
    params.require(:account).permit(%i[password password_confirmation current_password])
  end
end

app/views/accounts/shared/_account_panel.haml
.account-page
  .container
    .row
      .col-12.col-sm-4.col-md-3
        .hello-text
          = t('hello') + ','
          = @current_account.name
          %br
          %small= @current_account.email

        %ul.list-unstyled.account-menu
          %li{ class: ('current' if @account_action == 'dashboard') }
            = link_to accounts_dashboard_path do
              %i.fa.fa-user-circle-o
              = t('dashboard')

          %li{ class: ('current' if @account_action == 'edit') }
            - edit_link = @current_account.vat_customer? ? edit_vat_account_path : edit_account_path

            = link_to edit_link do
              %i.fa.fa-address-card-o
              = t('edit_your_account')

          %li{ class: ('current' if @account_action == 'edit_password') }
            = link_to edit_password_account_path do
              %i.fa.fa-lock
              = t('change_password')

          %li.divider

          %li{ class: ('current' if @account_action == 'shipping_addresses') }
            = link_to accounts_shipping_addresses_path do
              %i.fa.fa-truck
              = t('shipping_addresses')

          %li.divider

          %li{ class: ('current' if @account_action == 'orders') }
            = link_to accounts_orders_path do
              %i.fa.fa-archive
              = t('order_list')

      .col-12.col-sm-8.col-md-9
        .account-content
          = yield :account_content

app/views/accounts/shared/_links.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br


- if devise_mapping.registerable? && controller_name != 'registrations' # TODO remove this in the login view
  = link_to "Sign up", new_registration_path(resource_name)
  %br


- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br

- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br

- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br

- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br

app/views/accounts/shared/_orders_table.haml
-# this partial requires the following locals:
-# orders => a collection of orders
-# collapsed => boolean (defaults to true), if true the orders details will be collapsed

- collapsed ||= true

- if orders.size > 0
  .orders
    - orders.each do |order|
      .single-order
        .row
          .col-7
            %small.hidden-xs=t("order_date")
            %b=l(order.created_at, format: :base)
          .col-5.text-right
            %small.hidden-xs=t("order_code")
            %b=order.custom_id

        .row
          -# left half with buttons
          .col-6
            = link_to accounts_order_path(order), class: "btn btn-default btn-sm" do
              %i.fa.fa-plus.mr-1
              = t("order_details")

            = link_to "#order-#{order.id}", data: {toggle: "collapse"}, class: "btn btn-default btn-sm my-2 ml-3" do
              %i.fa.fa-caret-down.mr-1
              = t("preview")

            - if !order.cancelled? && !order.paid?
              = link_to payment_accounts_order_path(id: order), class: "btn btn-success btn-sm my-2 ml-3" do
                %i.fa.fa-credit-card.mr-1
                = t('conclude_payment')

          - # right half sith number, status and total
          .col-6.text-right
            .my-1
              .hidden-xs= t('order_status')

              %span.label{ class: "label-" + order_status_class(order.status_name) }
                = t(order.status_name.parameterize.underscore)

            = "#{t("total")}:"
            %b= number_to_currency(order.with_vat ? order.total : order.total_without_vat)


        .collapse{ id: "order-#{order.id}", class: ('in' if !collapsed) }
          %table.table.order-products
            - order.order_items.each do |item|
              %tr
                %td.image
                  - if (image = item.product.images.first).present?
                    = image_tag(image.url('50x50'))
                %td.name= item.name
                %td.text-right.price= number_to_currency item.price

            %tr
              %td.text-right{ colspan: 3 }
                .row
                  = render 'orders/total_recap', order: order

- else
  %p.text-center
    = t("order_list_empty")

app/views/accounts/shared/_register_box.haml
.col.col-sm-6.my-4
  %h4= t('register')
  %p= raw t('create_new_account_infos')

  = link_to new_account_registration_path, class: 'register-btn' do
    = raw t('register_now_divider')

app/views/accounts/shared/_unpaid_orders.haml
- if @current_account.present? && (unpaid_orders = @current_account.orders.active.unpaid).present?
  .my-3
    - message = t("unpaid_orders", count: unpaid_orders.size)
    - message += "<ul class='list-inline mt-2'>"
    - unpaid_orders.each do |order|
      - message += "<li><a class='btn btn-sm btn-danger' href='#{accounts_order_path(order)}'><i class='fa fa-archive mr-2'></i>#{order.custom_id}</a></li>"
    - message += "</ul>"
    = flash_danger(message)