config/routes.rb
#
Rails.application.routes.draw do
  # redirects to the appropriate lang
  get '', to: 'frontend#redirect_lang'

  # Start localized routes
  scope '/:locale', locale: /#{Ecommerce.find(ENV['ECOMMERCE_ID']).locales.join('|')}/ do
    # devise
    devise_for :accounts, skip: :registrations, controllers: {
      sessions: 'accounts/sessions',
      passwords: 'accounts/passwords'
    }, path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'password'
      # , confirmation: 'verification',
      # registration: 'register', edit: 'edit'
    }
    devise_scope :account do
      # devise registration
      resource :account_registration, only: [:new], path: "accounts", path_names: {new: "register"}, controller: 'accounts/registrations'
      post "/accounts", controller: "accounts/registrations", action: :create_base, as: :account_registration
      get "/accounts/register/sign_up_vat", controller: "accounts/registrations", action: :new_vat, as: :new_vat_account_registration
      post "/accounts/register_vat", controller: "accounts/registrations", action: :create_vat, as: :vat_account_registration

      resource :account, only: [:edit, :update] do
        get :edit_vat
        get :edit_password
        match :update_vat, via: [:put, :patch]
        match :update_password, via: [:put, :patch]
      end
      # get "/accounts/edit", controller: "accounts", action: :edit, as: :edit_account
      # match "/accounts", controller: "accounts", action: :update, as: :account, via: [:put, :patch]
    end

    # additional devise custom routes
    # namespace :accounts, as: "account", module: nil do
    #   namespace :register, as: "registration", module: "accounts/registrations" do
    #     # get "/accounts/register/sign_up_vat", action: :new_vat, as: :new_vat_account_registration
    #     resource :billing_address, only: [:new, :edit, :update]
    #   end
    # end

    # end devise


    namespace :accounts do
      get :dashboard

      resources :orders, only: [:index, :show] do
        member do
          match :cancel, via: [:put, :patch]
          get :payment
          post :payment, action: :update_payment, as: "update_payment"
        end
      end

      resources :shipping_addresses, except: [:show] do
        match :set_as_default, on: :member, via: [:patch, :put]
      end
    end


    scope module: 'frontend' do
      root to: 'pages#index'
      resources :pages, only: [:show]

      resources :categories, only: [:index, :show]
      resources :products, only: [:show] do
        collection do
          get :price_calc
        end
      end

      # cities and provinces routes
      namespace :addresses do
        # get ":country_id/provinces", action: "provinces", as: :provinces
        get ":province_name/cities", action: "cities", as: :cities
        get ":province_name/:city_name/suggest-cap", action: "suggest_cap", as: :suggest_cap
      end

      namespace :cart do
        root action: :show, as: :show
        post 'add_product/:product_id', action: :add_product, as: :add_product
        delete 'remove_item/:item_id', action: :remove_item, as: :remove_item
        # adds more products via get url
        get 'add_products/:product_ids', action: :add_products_from_url, as: :add_products
        # updates the cart quantities and starts the checkout process
        match '', action: :update, as: :update, via: [:patch, :put]

        # devise registraion and login from the cart
        devise_scope :account do
          namespace :sessions do
            post :create
          end
          namespace :registrations do
            get  :login_or_register
            get  :login_or_register_vat
            post :create_customer
            post :create_vat_account
          end
        end

        # ship address
        get :missing_details
        match :fill_details, via: [:put, :patch]

        get :change_shipping
        post :update_shipping

        get :confirm
        match :make_order, via: [:get, :post]  # final update action that will update the shipping/payment or generate the order
                                               # the GET method is mapped too to correctly intercept the "go back" buttons, a GET request shoul be redirected to the :confirm action
      end

      # path for posting contact forms
      namespace :contacts do
        # post :standard
        post :dynamic, :newsletter
      end

      scope module: "payments" do
        # /en/paga/81/ORD-4973/91.21
        get "paga/:payment_id/:custom_id/:total", action: :external_payment, constraints: {total: /\d+\.\d{2}/}
      end

    end

    # localized error pages
    get '*path', to: 'exceptions#not_found'
  end
  # end localized routes


  # non localized error pages
  get '*path', to: 'exceptions#not_found'
  # Rails expects the error pages to be served from /<error code>.
  match '400', to: 'exceptions#not_found', via: :all
  # error 500 is managed by the file in the public folder, a server error should render a static page!

end

app/views/frontend/pages/parts/_banner.haml
- # ============================================================================
- # though we could use this partial directly, i strongly advised against it.
- # call this partial from 'banner' or 'fullwidth_banner' instead.

- # for this partial to work, the following locals should be passed:
- # sitemap (a Sitemap instance)

- # the slider plugin used is RoyalSlider
- # http://dimsemenov.com/plugins/royal-slider/documentation/

- # each children of the sitemap passed is considered to be a single slide
- # each slide can use the following sitemap attributes
- # extend and change this partial in the future according to your needs.

- # sitemap.title:                 is the main title into the slide
- # sitemap.short_description:     is a string to put under th emain title (sub-title)
- # sitemap.description:           is a longer text that can be added in front of the banner
- # sitemap.link:                  is the banner destination
- # sitemap.link_title:            is the link text if a link is provided
- # sitemap.images.normals.first:  is the first image with typology 'normal' loaded into each child

- # you can set slide's text color individually using { color: '#fff' }
- # ============================================================================


-# cache cache_for_locale("page_content-#{sitemap.cache_key}") do
- defaults = "{ layout: #{sitemap.layout.gsub('banner', '').gsub(/_\z/, '')}, height: 400, transition_type: 'fade', show_arrow: 'true', show_dots: 'true', autoplay: 'true', align: 'center', color: '#fff' }"
- options = get_layout_options(sitemap, YAML.safe_load(defaults))

- images = sitemap.children.joins(:images).where(attachments: { typology_id: 0 }).uniq

- # bullet should be disabled if:
- # 1. options['show_dots'] NOT set to true, OR
- # 2. total images not more than 1, regardless options['show_dots']
- options['show_dots'] = options['show_dots'].to_s == 'true' ? (images.count > 1 ? 'bullets' : 'none') : 'none'

- if images.present?
  - if options['layout'] == 'full_width'
    - # full-width banner
    .height-width
      = render 'frontend/pages/parts/banner_content', sitemap: sitemap, images: images, options: options

  - elsif options['layout'] == 'full_screen'
    - # full-screen banner
    .fullscreen-banner-container
      = render 'frontend/pages/parts/banner_content', sitemap: sitemap, images: images, options: options

  - else
    - # normal banner
    .container
      .row
        .col.px-0.px-md-3
          = render 'frontend/pages/parts/banner_content', sitemap: sitemap, images: images, options: options

app/views/frontend/pages/parts/_banner_content.haml
-# cache cache_for_locale("page_content-#{sitemap.cache_key}") do
.banner.royalSlider.rsDefault{ id: "section-banner-#{sitemap.id}", style: "min-height: #{options['height']}px", data: { transition_type: options['transition_type'], show_arrow: options['show_arrow'].to_s, autoplay: options['autoplay'].to_s, show_dots: options['show_dots'].to_s, fullscreen: (options['layout'] == 'full_screen' ? true : false).to_s } }
  - images.each do |slide|
    - # draw each image content
    - defaults = "{ color: '#{options['color']}', align: '#{options['align']}' }"
    - options = options.merge(get_layout_options(slide, YAML.safe_load(defaults)))

    .slide.rsContent
      = image_tag(slide.images.normals.first.url('1800'), class: 'rsImg img-fluid')

      .position-absolute.slide-content{ class: "content-#{options['align']}", style: "text-align: #{options['align']}" }
        .container
          .row{ class: banner_alignment(options['align']) }
            .col-12.col-md-4
              %h2.slide-title{ style: "color: #{options['color']}" }= slide.title

              - if (subtitle = slide.short_description).present?
                %h4.slide-subtitle{ style: "color: #{options['color']}" }= subtitle

              - if (text = slide.description).present?
                .slide-text{ style: "color: #{options['color']}" }= raw text

              - if (link = slide.link).present?
                .slide-link= link_to slide.link_title, link, target: slide.link_target

- content_for :javascripts do
  :javascript
    var $el = $("#section-banner-#{sitemap.id}");
    // var $h = ;

    if ($el.data('fullscreen') == true) {
      $('.fullscreen-banner-container').height($(window).height());
      $h = $(window).height()
    } else {
      $h = '400'
    }

    $el.royalSlider({
      imageScaleMode: 'fill',
      transitionType: $el.data('transition-type'),
      arrowsNav: $el.data('show-arrow'),
      slidesSpacing:  0,
      loopRewind:     true,
      controlNavigation: $el.data('show-dots'),
      autoScaleSliderHeight: $h,
      imageAlignCenter: true,
      autoplay: {
        enabled:      $el.data('autoplay'),
        stopAtAction: false,
        pauseOnHover: false,
        delay:        6000
      }
    });

    $el.royalSlider('updateSliderSize', true);

app/views/frontend/pages/parts/_blog.haml
#blog-section
  - if (blogs = section.children).present?
    .container
      .row
        .col-12
          - blogs = blogs.page(params[:page]).per(8)
          - blogs.each do |blog|
            .list-entry
              .page-title
                = link_to page_path(blog) do
                  %h2= blog.title
                  .entry-dateline-link
                    = blog.date&.strftime("%B %d, %Y")

              - if (imgs = blog.images).present?
                .page-content.text-center
                  .content-image
                    = link_to page_path(blog) do
                      = image_tag imgs.first.url

              - if (content = truncate(blog.description, length: 250, :escape => false)).present?
                .page-content.description
                  = link_to page_path(blog) do
                    - simple_format(content.html_safe)
                    = parse_content(simple_format(content.html_safe), blog)

                = link_to t('read_more'), page_path(blog), class: 'entry-more-link'

          .pager
            - unless blogs.first_page?
              = link_to page_path(id: @page.to_param, page: blogs.prev_page), class: "newer pull-left" do
                %i.fa.fa-angle-left
                Newer Posts

            - unless blogs.last_page?
              = link_to page_path(id: @page.to_param, page: blogs.next_page), class: "older pull-right" do
                Older Posts
                %i.fa.fa-angle-right

app/views/frontend/pages/parts/_embed_product.haml
.embed-product
  -# %h2.product-title= link_to product.name, product_path(product)

  .row.mt-3.align-items-center
    .col-12.col-md-7
      .product-image
        = link_to product_path(product) do
          - image_url = (images = product.images.normals).present? ? images&.first&.url('393') : '//via.placeholder.com/393x262'
          = image_tag image_url, class: 'img-fluid'

    .col-12.col-md-4.embed-content
      %h2= product.name

      .price
        - # show list price if it present, alongside with the discount in percent
        - if product.has_discount?
          .normal-price
            = number_to_currency product.price_list
            %span.discount #{t 'products.discount', disc: product.discount.to_s + "%" }

        .price-with-vat
          = number_to_currency product.price_with_vat
          %small= t('include_vat')

        .price-without-vat
          = number_to_currency product.price_without_vat
          %small= "+ #{t("vat_iva")}"

      = simple_format(truncate product.description, length: 255)

      = link_to t('products.buy_now'), product_path(product), class: 'embed-btn'

  -# .lorem= link_to product_path(product)

      -# .description= simple_format product.description_short.html_safe

      -# - if product.purchasable?
      -#   = form_tag cart_add_product_path(product_id: product.id), remote: true, class: 'order-form' do
      -#     .product-in-cart-alert{ id: "product-in-cart-alert-#{product.id}" }
      -#       - if @current_cart.items.collect(&:product_id).include?(product.id)
      -#         = render 'frontend/products/in_cart_alert'

      -#     .form-group
      -#       = label_tag :quantity, "#{t('products.quantity')}:"
      -#       = hidden_field_tag :redirect_url, "#{request.original_url}"

      -#       .clearfix
      -#         .pull-left
      -#           = quantity_field_for product

app/views/frontend/pages/parts/_event.haml
#event-list
  - if (events = section.children).present?
    .container
      .row
        .col-12
          - events.each do |event|
            .list-entry
              .page-title
                .entry-dateline-link= event.date&.strftime("%B %d, %Y")

                %h2= link_to event.text, page_path(event)

              - if (content = truncate(event.short_description, length: 250)).present?
                .page-content.description
                  = link_to page_path(event) do
                    = simple_format(content.html_safe)

                = link_to t('read_more'), page_path(event), class: 'entry-more-link'

app/views/frontend/pages/parts/_gallery.haml
- if (images = section.images.normals).present?
  %section
    #gallery
      .container
        .row
          .col-12
            %hr.divider

            .row
              - images.each do |image|
                .col-sm-4
                  .thumb-container.square-thumb
                    = image_tag image.url('391x391'), href: image.url

- content_for :stylesheets do
  = stylesheet_link_tag 'magnific-popup'

- content_for :javascripts do
  = javascript_include_tag 'jquery.magnific-popup.min'

  :javascript
    $('#gallery').magnificPopup({
      delegate: 'img',
      type: 'image',
      closeBtnInside: false,
      gallery: {
        enabled: true,
        tCounter: ''
      }
    });

app/views/frontend/pages/parts/_image_links.haml
- defaults = "{ show_title: 'true', per_row: 4, show_description: 'true', image_as_bg: false }"
- options = get_layout_options(sitemap, YAML.safe_load(defaults))

- image_contents = sitemap.children

- # render 'page_content' partial to ensure it has consistent formatting & styling
= render 'frontend/pages/parts/page_content', sitemap: sitemap, options: options

- # important!
- # always make sure options have correct value type, e.g. to_i if you need integer
- # this is to handle when admin input wrong type of value
.container.my-5.image-links{ id: "section-image-links-#{sitemap.id}" }
  .row
    - klass = options['per_row'].to_i > 1 ? "col-12 col-md-#{(12 / options['per_row'].to_i).floor}" : nil

    - image_contents.includes(:children).each do |child|
      - next unless (images = child.images&.normals).present?

      .col{ class: klass }
        = link_to child.link, target: child.link_target do
          - img = image_tag images.first.url('300'), class: 'img-fluid'

          - if options['image_as_bg'].to_s == 'true'
            - container_class = 'link-bg-container'
          - else
            - container_class = 'link-container'

          .text-center{ class: container_class }
            .image-container
              = img

            .link-content
              - if options['show_title'].to_s == 'true'
                %h4= child.title&.html_safe

              - if options['show_description'].to_s == 'true'
                = simple_format child.description

app/views/frontend/pages/parts/_links.haml
- defaults = "{ button_class: 'btn btn-danger' }"
- options = get_layout_options(sitemap, YAML.safe_load(defaults))

- # render 'page_content' partial to ensure it has consistent formatting & styling
= render 'frontend/pages/parts/page_content', sitemap: sitemap, options: options

- if (links = sitemap.children).present?
  .container.my-2{ id: "section-link-#{sitemap.id}" }
    .row
      - links.each do |link|
        .col.text-center.my-3
          = link_to link.link, class: btn_class do
            = link.link_title

app/views/frontend/pages/parts/_map.haml
- # ============================================================================
- # put your map theme js in 'app/assets/javascripts/frontend/map-styles'.
- # filename should be the equal to options['map_style'].parameterize
- # e.g. if we have map_style = 'simplified grayscale' then the file should be
- # 'app/assets/javascripts/frontend/map-styles/simplified_grayscale.js'
- # ============================================================================


-# - cache cache_for_locale("page_content-#{sitemap.cache_key}") do
- defaults = "{ coordinate: '41.905753,12.4818493', map_style: 'simplified grayscale' }"
- options = get_layout_options(sitemap, YAML.safe_load(defaults))
- coord = options['coordinate'].split(',').map{ |c| c.strip }

- # render 'page_content' partial to ensure it has consistent formatting & styling
= render 'frontend/pages/parts/page_content_categories', sitemap: sitemap, options: options

.container
  .row
    .col
      .map-container
        #map

- content_for :javascripts do
  = javascript_include_tag "frontend/map-styles/#{options['map_style'].parameterize}"

  :javascript
    function initMap() {
      var myLatLng = {
        lat: #{coord[0]},
        lng: #{coord[1]}
      };

      var map = new google.maps.Map(document.getElementById('map'), {
        center: myLatLng,
        zoom: 15,
        styles: map_style_opts
      });

      var marker = new google.maps.Marker({
        position: myLatLng,
        title: "Football Player"
      });
    }

  = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyAPfoCD8LCOvGaxO-slw_nAZpGWbsPI70o&callback=initMap'

app/views/frontend/pages/parts/_page_content.haml
- # ============================================================================
- # by default, needed attributes are:
- # * sitemap.images.logos.first.url: icon for title
- # * sitemap.title:                  title
- # * sitemap.short_description:      subtitle
- # * sitemap.description:            content
- # ============================================================================


- unless defined?(options)
  - defaults = "{ logo_as_title_bg: false }"
  - options = get_layout_options(sitemap, YAML.safe_load(defaults))

- image = sitemap.images&.logos&.first
- title = sitemap.title
- subtitle = sitemap.short_description
- content = sitemap.description
- date = sitemap.date

- if image.present? || title.present? || subtitle.present? || content.present?
  .container.section{ id: "section-content-#{sitemap.id}" }
    .row
      .col
        .page-content
          .title
            - # icon, if any
            - if image.present? && options['logo_as_title_bg'].to_s == 'true'
              .header-image-container{ style: "background-image: url(#{asset_path(image.url('x150'))})" }
                .header-content
                  - # title, if any
                  - if title.present?
                    %h2= title.html_safe

                  - # subtitle, if any
                  - if subtitle.present?
                    %h3= parse_content subtitle, sitemap

            - else
              - if image.present?
                .title-icon
                  = image_tag image.url('x150')

              - # title, if any
              - if title.present?
                %h2= title.html_safe

              - # subtitle, if any
              - if subtitle.present?
                %h3= parse_content subtitle, sitemap

            - # date, if any
            - if date.present?
              .date= date.strftime("%B %d, %Y")

          - # content
          - if content.present?
            .content
              = parse_content content, sitemap

app/views/frontend/pages/parts/_page_content_categories.haml
- # ============================================================================
- # by default, needed attributes are:
- # * sitemap.images.logos.first.url: icon for title
- # * sitemap.title:                  title
- # * sitemap.short_description:      subtitle
- # * sitemap.description:            content
- # ============================================================================


- unless defined?(options)
  - defaults = "{ logo_as_title_bg: false }"
  - options = get_layout_options(sitemap, YAML.safe_load(defaults))

- image = sitemap.images&.logos&.first
- title = sitemap.title
- subtitle = sitemap.short_description
- content = sitemap.description
- date = sitemap.date

- if image.present? || title.present? || subtitle.present? || content.present?
  .container.categories-rightop{ id: "section-content-#{sitemap.id}" }
    .row
      .col
        .page-content
          .title
            - # icon, if any
            - if image.present? && options['logo_as_title_bg'].to_s == 'true'
              .header-image-container{ style: "background-image: url(#{asset_path(image.url('x150'))})" }
                .header-content
                  - # title, if any
                  - if title.present?
                    %h2= title.html_safe

                  - # subtitle, if any
                  - if subtitle.present?
                    %h3= parse_content subtitle, sitemap

            - else
              - if image.present?
                .title-icon
                  = image_tag image.url('x150')

              - # title, if any
              - if title.present?
                %h2= title.html_safe

              - # subtitle, if any
              - if subtitle.present?
                %h3= parse_content subtitle, sitemap

            - # date, if any
            - if date.present?
              .date= date.strftime("%B %d, %Y")

          - # content
          - if content.present?
            .content
              = parse_content content, sitemap

app/views/frontend/pages/parts/_page_content_contact.haml
- # ============================================================================
- # by default, needed attributes are:
- # * sitemap.images.logos.first.url: icon for title
- # * sitemap.title:                  title
- # * sitemap.short_description:      subtitle
- # * sitemap.description:            content
- # ============================================================================


- image = sitemap.images&.logos&.first
- title = sitemap.title
- subtitle = sitemap.short_description
- content = sitemap.description
- date = sitemap.date

- if image.present? || title.present? || subtitle.present? || content.present?
  .container.section.contact-leftside{ id: "section-content-#{sitemap.id}" }
    .page-content
      .title
        - # icon, if any
        - if image.present?
          .title-icon
            = image_tag image.url('x150')

        - # title, if any
        - if title.present?
          %h2= title.html_safe

        - # subtitle, if any
        - if subtitle.present?
          %h3= parse_content subtitle, sitemap

        - # date, if any
        - if date.present?
          .date= date.strftime("%B %d, %Y")

      - # content
      - if content.present?
        .content
          = parse_content content, sitemap

app/views/frontend/pages/parts/_product_list_card.haml
.container.products-list.product-list-card{ id: "section-products-#{sitemap&.id}" }
  - products.in_groups_of(options['per_row'], false).each do |products_group|
    .row
      - products_group.each do |product|
        .col-6{ class: "col-lg-#{(12 / options['per_row']).floor}" }
          - klass = 'card product-card'
          - klass += ' with-rollover-image' if (rollover_image = product.images.rollovers.first).present?

          = link_to product_path(product), class: klass, style: "background-color: #{options['bg_color']}", onmouseover: "this.style.backgroundColor = '#{options['hover_bg_color']}'", onmouseout: "this.style.backgroundColor = '#{options['bg_color']}'" do
            - if (preview = product.images.normals.first).present?
              .card-img-top.position-relative
                .image-container
                  = image_tag preview.url('200x200#'), class: 'position-relative first-image img-fluid'

                  - if rollover_image.present?
                    = image_tag rollover_image.url('200x200#'), class: 'position-absolute second-image img-fluid'

            - else
              = image_tag '//via.placeholder.com/200x200', class: 'card-img-top position-relative img-fluid'

            - if product.has_discount?
              .discount-badge
                = "-#{product.discount_percentage.to_s}%"

            - if !product.available?
              .availability-badge{ class: "badge-#{product.availability}" }
                %span= t "products.availability.#{product.availability}"

            .card-body
              %h3.product-name= product.name

              %h4.product-sku= product.code

              %h5.product-price
                - if !product.has_reseller_price? && product.has_discount?
                  %span.original-price= number_to_currency product.price_table.price_list

                %span.price= number_to_currency product.price_with_vat

app/views/frontend/pages/parts/_product_lists.haml
- # ============================================================================
- # for this partial to work, the following locals should be passed:
- # sitemap ( a Sitemap instance )

- # the extra_1 of the sitemap passed, should contain a list of product ids separated by comma
- # sitemap short description will be used as title, if provided
- # here's an example of a valid list: "140, 156, 208, 1130, 6820"

- # extend this partial according to your needs, this is just a minimal structure
- # ============================================================================


- defaults = "{ show: 'featured', layout: 'card', limit: 6, per_row: 6, bg_color: '#f7f7f7', hover_bg_color: '#fff', use_paginator: false }"
- options = get_layout_options(sitemap, YAML.safe_load(defaults))

- options['limit'] = options['limit'].to_i
- options['per_row'] = options['per_row'].to_i

- products = get_product_list(options['show'], options['limit'])
- if products.present?
  - # render 'page_content' partial to ensure it has consistent formatting & styling
  = render 'frontend/pages/parts/page_content', sitemap: sitemap, options: options

  = render "frontend/pages/parts/product_list_#{options['layout']}", sitemap: sitemap, products: products, options: options