config/routes.rb
#
Rails.application.routes.draw do
  # redirects to the appropriate lang
  get '', to: 'frontend#redirect_lang'

  # Start localized routes
  scope '/:locale', locale: /#{Ecommerce.find(ENV['ECOMMERCE_ID']).locales.join('|')}/ do
    # devise
    devise_for :accounts, skip: :registrations, controllers: {
      sessions: 'accounts/sessions',
      passwords: 'accounts/passwords'
    }, path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'password'
      # , confirmation: 'verification',
      # registration: 'register', edit: 'edit'
    }
    devise_scope :account do
      # devise registration
      resource :account_registration, only: [:new], path: "accounts", path_names: {new: "register"}, controller: 'accounts/registrations'
      post "/accounts", controller: "accounts/registrations", action: :create_base, as: :account_registration
      get "/accounts/register/sign_up_vat", controller: "accounts/registrations", action: :new_vat, as: :new_vat_account_registration
      post "/accounts/register_vat", controller: "accounts/registrations", action: :create_vat, as: :vat_account_registration

      resource :account, only: [:edit, :update] do
        get :edit_vat
        get :edit_password
        match :update_vat, via: [:put, :patch]
        match :update_password, via: [:put, :patch]
      end
      # get "/accounts/edit", controller: "accounts", action: :edit, as: :edit_account
      # match "/accounts", controller: "accounts", action: :update, as: :account, via: [:put, :patch]
    end

    # additional devise custom routes
    # namespace :accounts, as: "account", module: nil do
    #   namespace :register, as: "registration", module: "accounts/registrations" do
    #     # get "/accounts/register/sign_up_vat", action: :new_vat, as: :new_vat_account_registration
    #     resource :billing_address, only: [:new, :edit, :update]
    #   end
    # end

    # end devise


    namespace :accounts do
      get :dashboard

      resources :orders, only: [:index, :show] do
        member do
          match :cancel, via: [:put, :patch]
          get :payment
          post :payment, action: :update_payment, as: "update_payment"
        end
      end

      resources :shipping_addresses, except: [:show] do
        match :set_as_default, on: :member, via: [:patch, :put]
      end
    end


    scope module: 'frontend' do
      root to: 'pages#index'
      resources :pages, only: [:show]

      resources :categories, only: [:index, :show]
      resources :products, only: [:show] do
        collection do
          get :price_calc
        end
      end

      # cities and provinces routes
      namespace :addresses do
        # get ":country_id/provinces", action: "provinces", as: :provinces
        get ":province_name/cities", action: "cities", as: :cities
        get ":province_name/:city_name/suggest-cap", action: "suggest_cap", as: :suggest_cap
      end

      namespace :cart do
        root action: :show, as: :show
        post 'add_product/:product_id', action: :add_product, as: :add_product
        delete 'remove_item/:item_id', action: :remove_item, as: :remove_item
        # adds more products via get url
        get 'add_products/:product_ids', action: :add_products_from_url, as: :add_products
        # updates the cart quantities and starts the checkout process
        match '', action: :update, as: :update, via: [:patch, :put]

        # devise registraion and login from the cart
        devise_scope :account do
          namespace :sessions do
            post :create
          end
          namespace :registrations do
            get  :login_or_register
            get  :login_or_register_vat
            post :create_customer
            post :create_vat_account
          end
        end

        # ship address
        get :missing_details
        match :fill_details, via: [:put, :patch]

        get :change_shipping
        post :update_shipping

        get :confirm
        match :make_order, via: [:get, :post]  # final update action that will update the shipping/payment or generate the order
                                               # the GET method is mapped too to correctly intercept the "go back" buttons, a GET request shoul be redirected to the :confirm action
      end

      # path for posting contact forms
      namespace :contacts do
        # post :standard
        post :dynamic, :newsletter
      end

      scope module: "payments" do
        # /en/paga/81/ORD-4973/91.21
        get "paga/:payment_id/:custom_id/:total", action: :external_payment, constraints: {total: /\d+\.\d{2}/}
      end

    end

    # localized error pages
    get '*path', to: 'exceptions#not_found'
  end
  # end localized routes


  # non localized error pages
  get '*path', to: 'exceptions#not_found'
  # Rails expects the error pages to be served from /<error code>.
  match '400', to: 'exceptions#not_found', via: :all
  # error 500 is managed by the file in the public folder, a server error should render a static page!

end

app/controllers/frontend/addresses_controller.rb
class Frontend::AddressesController < FrontendController

  # there's no need to get the provinces since we assume that the only provinces are the italians

  # def provinces
  #   @country = Country.find(params[:country_id])
  #   @provinces = @country.provinces
  # end


  def cities
    @province = Province.find_by_full_description(params[:province_name])
    @cities = @province.cities

    respond_to do |format|
      format.html{ render layout: false}
    end
  end


  def suggest_cap
    @province = Province.find_by_full_description(params[:province_name])
    @city = @province.cities.find_by_name(params[:city_name]) if @province 

    if @city
      render text: @city.cap
    else
      render nothing: true, status: 404
    end


  end


end

app/controllers/frontend/cart/addresses_controller.rb
class Frontend::Cart::AddressesController < Frontend::CartController

  

end

app/controllers/frontend/cart/registrations_controller.rb
#
class Frontend::Cart::RegistrationsController < Devise::RegistrationsController
  add_breadcrumb I18n.t('my_cart'), :cart_show_path
  add_breadcrumb I18n.t('login_or_register')
  include AccountRegistrable

  before_action :set_cart_progress, :proceed_if_logged_in

  # first step of the checkout
  def login_or_register
    build_resource({})
    yield resource if block_given?
    respond_with resource
  end

  # first step of the checkout for vat accounts registration
  def login_or_register_vat
    build_resource({})
    yield resource if block_given?
    respond_with resource
  end

  # creates the account of a "cliente"
  def create_customer
    @additional_resource_params = {
      role: "cliente",
      ecommerce_id: @current_ecommerce.id,
      parent_id: EcommerceConfig.store_id
    }
    @failure_view = "login_or_register"
    configure_permitted_parameters
    create_account
  end

  # creates the account of a "vat_customer"
  def create_vat_account
    @additional_resource_params = {
      role: "vat_customer",
      ecommerce_id: @current_ecommerce.id,
      parent_id: EcommerceConfig.store_id
    }
    @failure_view = "login_or_register_vat"
    configure_permitted_parameters
    create_account
  end

  private

  # updates the cart progress
  def set_cart_progress
    @current_cart.set_progress!(ShoppingCart::Progresses.registration)
  end

  # if the user is logged in and can purchase there's no reason to show anything of this controller
  def proceed_if_logged_in
    redirect_to next_cart_step if @current_account.present?
  end

  protected

  #
  def after_sign_up_path_for(resource)
    next_cart_step
  end

  #
  def next_cart_step
    @current_account.can_order? ? cart_confirm_path : cart_missing_details_path
  end
end

app/controllers/frontend/cart/sessions_controller.rb
# this controller manages the login from the cart

class Frontend::Cart::SessionsController < Devise::SessionsController

  # # POST /resource/sign_in
  # def create
  #   self.resource = warden.authenticate!(auth_options)
  #   set_flash_message!(:notice, :signed_in)
  #   sign_in(resource_name, resource)
  #   yield resource if block_given?
  #   respond_with resource, location: after_sign_in_path_for(resource)
  # end


  def after_sign_in_path_for(resource)
    resource.can_order? ? cart_confirm_path : cart_missing_details_path
  end
  
end

app/controllers/frontend/categories_controller.rb
#
class Frontend::CategoriesController < FrontendController
  include FrontendHelper
  include ProductHelper
  include ProductAttributeHelper

  add_breadcrumb I18n.t('products.products'), :categories_path

  #
  def index
    @sitemap = @all_pages.find_by layout: 'root_category'
    defaults = "{
      show_products: 'featured',
      layout: 'card',
      per_page: 10,
      per_row: 4,
      bg_color: '#fff',
      hover_bg_color: '#eee',
      sort: 'latest',
      use_sidebar: true
    }"
    @options = get_layout_options(@sitemap, YAML.safe_load(defaults))
    @products = get_product_list(@options['show_products'], @options['per_page'], @options['sort'])

    if @options['per_page'].to_i > 0
      @products = @products.per(@options['per_page'].to_i)
    end
  end

  #
  def show
    @category = @current_ecommerce.categories.find(params[:id])

    # breadcrumbs
    @category.ancestors.active.order(lft: :asc).each do |cat|
      add_breadcrumb cat.name, category_path(id: cat)
    end

    add_breadcrumb @category.name, category_path(id: @category)

    @sitemap = @all_pages.find_by layout: 'child_category'
    defaults = "{
      show_products: 'featured',
      layout: 'card',
      per_page: 10,
      per_row: 4,
      bg_color: '#fff',
      hover_bg_color: '#eee',
      sort: 'latest',
      use_sidebar: true
    }"
    @options = get_layout_options(@sitemap, YAML.safe_load(defaults))
    @products = @category.products.non_add_ons.page(params[:page])

    if @options['per_page'].to_i > 0
      @products = @products.per(@options['per_page'].to_i)
    end
  end
end

app/controllers/frontend/contacts_controller.rb
#
class Frontend::ContactsController < FrontendController
  #
  def dynamic
    session[:contact_standard] = params[:contact].permit(:email, :name, :message, :telephone, :privacy).merge({ecommerce_id: @current_ecommerce.id, typology: Contact.typologies["Contatto Generico"], remote_addr: request.remote_ip })
    @contact = Contact.new(session[:contact_standard])
    session[:dynamic_contact] = params[:contact].permit(
      :name, :surname, :telephone, :phone, :company, :address, :city, :province,
      :cap, :country, :email, :message, :budget, :region, :telephone_prefix,
      :phone_prefix, :birth_date, :form_id, :typology, :privacy
    ).merge({
      ecommerce_id: @current_ecommerce.id,
      remote_addr: request.remote_ip
    })
    @contact = Contact.new(session[:dynamic_contact])

    if @contact.save
      session[:dynamic_contact] = nil
      flash[:success] = I18n.t('contacts.success')
      render layout: false
      NotifierMailer.mail_info(@contact).deliver_now
    else
      flash[:error] = @contact.errors.full_messages
      render layout: false
    end
  end

  #
  def newsletter
    session[:contact_newsletter] = params[:contact].permit(:email, :name, :surname, :privacy).merge({
      ecommerce_id: @sitemap_ecommerce.id,
      typology: Contact.typologies['Newsletter'],
      remote_addr: request.remote_ip })
    @contact = Contact.new(session[:contact_newsletter])

    respond_to do |f|
      if @contact.save
        f.js do
          session[:contact_newsletter] = nil
          flash.now[:success] = I18n.t("contacts.newsletter.success")
          render layout: false
          NotifierMailer.mail_info(@contact).deliver_now
        end
      else
        f.js do
          flash.now[:error] = @contact.errors.full_messages
          render layout: false
        end
      end
    end
  end
end

app/helpers/frontend_helper.rb
#
module FrontendHelper
  #
  #
  def viewport
    if @force_desktop_version
      'width=1200'
    else
      'width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0'
    end
  end

  # helper to build the title (used in association with the gem metamagic)
  def page_title_for(title, site)
    return site if title.blank?
    title = title.map(&:squish).compact.join(" - ") if title.is_a?(Array)
    title.include?(site) ? title : "#{title} - #{site}"
  end

  # javascript_include_tag and sylesheet_link_tag override to include assets ONLY ONCE
  # this allows to call those methods inside partials without worrying about assets repeating all over the page
  def javascript_include_tag(*sources)
    @included_javascripts ||= []
    sources.reject!{|s| @included_javascripts.include?(s)}
    @included_javascripts += sources
    super(*sources)
  end

  #
  def available_locales
    @current_ecommerce.locales.reject(&:empty?)
  end

  #
  def sylesheet_link_tag(*sources)
    @included_stylesheets ||= []
    sources.reject!{|s| @included_stylesheets.include?(s)}
    @included_stylesheets += sources
    super(*sources)
  end

  #
  def ecommerce_countries
    @_ecommerce_countries ||= Country.all.order("name").pluck(:name)
  end

  #
  def ecommerce_italian_provinces
    @_ecommerce_provinces ||= Province.joins(:country)
      .where(countries: { iso: 'IT' })
      .order('full_description').pluck(:full_description)
  end

  #
  def telephone_prefixes
    @_telephone_prefixes ||= PhonePrefix.order(:prefix).pluck(:prefix).uniq
  end

  #
  def sex_array
    ['M', 'F']
  end

  def account_panel
    content_for :account_content do
      yield
    end

    return render 'accounts/shared/account_panel'
  end


  def cart_panel
    content_for :cart_content do
      yield
    end
    return render partial: "frontend/cart/cart_panel"
  end



  def error_messages_for(record)
    return "" if record.errors.empty?
    # Don't use full_messages because it doesn't skip empty error messages
    messages = record.errors.messages.map do |k, error|
      error.map{|e| content_tag(:li, record.errors.full_message(k, e)) if e.present? }.join
    end.join

    sentence = I18n.t("errors.messages.not_saved",
                      count: record.errors.count,
                      resource: record.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button class="close" type="button" data-dismiss="alert" aria-hidden="true">&times;</button>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end



  def order_status_class(status_text)
    case status_text.parameterize.underscore
    when "annullato", "rimborsato"
      "default"
    when "spedito"
      "success"
    when "parzialmente_spedito", "fatturato", "in_attesa_di_spedizione", "pagato_in_lavorazione"
      "warning"
    when "in_attesa_di_pagamento"
      "danger"
    end
  end

  # take the passed dimension and translate it into a bootrap colum class
  # if not recognized, fallback to full width
  def translate_to_column(dimension)
    klass = case dimension
    when "full"
      klass = "col-sm-12"
    when "big"
      klass = "col-sm-8"
    when "half"
      klass = "col-sm-6"
    when "small"
      klass = "col-sm-4"
    else
      klass = "col-sm-12"
    end
    klass
  end

  # Set sitemap text or link
  def sitemap_text_or_link(sitemap)
    if sitemap.extra_1.present?
      sitemap.extra_1
    elsif sitemap.link.present?
      sitemap_layout = sitemap.parent.layout

      if %w(social).include?(sitemap_layout)
        link_to sitemap.link, target: sitemap.link_target do
          haml_tag :i, class: "fa fa-#{sitemap.text.parameterize}"
        end
      else
        link_to sitemap.text, sitemap.link, target: sitemap.link_target
      end
    else
      link_to sitemap.text, page_path(sitemap), target: sitemap.link_target
    end
  end

  # set option values for each layout
  def get_layout_options(sitemap = '{}', default_opts = '{}')
    opts =
      if sitemap.present? && sitemap&.sitemap_options.present?
        a = sitemap.sitemap_options.collect(&:options).map{ |a| { a['name'] => a['value'] } }
        Hash[*a.collect{ |h| h.to_a }.flatten].reject{ |k, v| v.blank? }
      else
        { }
      end

    default_opts.merge(opts)
  end

  #
  def show_breadcrumbs?
    # show breadcrumb if it's enabled on the ecommerceconfig
    # typically, we do not need to render breadcrumb on homepage & 404 page
    # default is to obey value set in config
    return false if @page.present? && @page.layout == 'homepage'
    return false if response.status == 404

    ENV['BREADCRUMBS']
  end

  #
  def reseller?
    account_signed_in? && current_account.custom_discount_typology == 'reseller'
  end

  #
  def cache_for_locale(cache_key)
    "#{cache_key}/#{I18n.locale.to_s.downcase}"
  end

  #
  def banner_alignment(align)
    arr = { left: 'start', right: 'end', center: 'center' }
    # class_name =
    #   case align
    #   when 'left' then 'start'
    #   when 'right' then 'end'
    #   else 'center'
    "justify-content-#{arr[align.to_sym]}"
  end

  def db_field_to_input(form, model_name, field_name, required=nil)
    # model_name = model_name.camelize
    field_type = model_name.constantize.columns_hash[field_name].type
    field_type =
      case field_type
      when :integer
        form.number_field field_name.to_sym, required: required, class: 'form-control', placeholder: t("#{model_name.pluralize.parameterize}.#{field_name}")
      when :text
        form.text_area field_name.to_sym, required: required, class: 'form-control', placeholder: t("#{model_name.pluralize.parameterize}.#{field_name}")
      else
        form.text_field field_name.to_sym, required: required, class: 'form-control', placeholder: t("#{model_name.pluralize.parameterize}.#{field_name}")
      end
  end

end

app/views/frontend/cart/_cart_panel.haml
- @body_class = 'cart-padded'

.cart-page
  .container
    .row
      .col.col-sm-8
        .cart-content
          - # unpaid orders reminder
          - unless @skip_unpaid_orders
            = render 'accounts/shared/unpaid_orders'

          = yield :cart_content

      - if @current_cart.items.size > 0
        .col.col-sm-4.rightbar
          .right-products
            = render 'frontend/cart/parts/items_list'
            %hr
            = render 'frontend/cart/parts/total_recap'

  / - if @current_cart.items.size > 0
  /   .mobile-recap
  /     .recap-bar
  /       .float-left
  /         %i.fa.fa-caret-up.mr-3
  /         =t("cart_summary")
  /         -# cart-quantity-badge is targeted by the javascript that updates the cart quantity, don't change or remove that class
  /         %span.cart-quantity-badge.badge.ml-1
  /           =@current_cart.items.size

  /       .float-right.recap-total
  /         =number_to_currency @current_cart.final_price

  /     .recap-scroll-wrapper
  /       .recap-items
  /         =render partial: "frontend/cart/parts/items_list"
  /       .recap-price-details
  /         =render partial: "frontend/cart/parts/total_recap"

app/views/frontend/cart/change_shipping.haml
- meta title: t("shipping"), description: t("shipping")

- content_for :javascripts do
  = javascript_include_tag "frontend/cart/shipping"

.cart-shipping
  = cart_panel do
    %h2= t("shipping_address")
    %p= t("please_note_this_is_the_postal")
    %b= t("shipping_address_delivery_item")


    = form_for @address, url: cart_update_shipping_path, html: { class: "form floating-labels" } do |f|
      = error_messages_for(@address)

      .my-4
        = render "accounts/shipping_addresses/shipping_fields", f: f

        .row
          .p-4.float-left= link_to t("go_back"), :back, class: "btn btn-default"
          .p-4.float-right= f.submit t("save_changes"), class: "btn btn-primary"

app/views/frontend/cart/confirm.haml
- meta title: t('checkout'), description: t('checkout')

= cart_panel do
  .cart-confirm
    = render 'frontend/cart/confirm_parts/promo'

    %hr
    %h2= t('checkout')

    = form_for @current_cart, url: cart_make_order_path, method: :post, html: { id: 'cart-form' } do |f|
      = error_messages_for @current_cart
      - # warning messages
      - @current_cart.warnings? # this will trigger the warnings callbacks and will populate the warning messages as necessary
      - if @current_cart.warnings.present?
        = flash_warning(@current_cart.warnings.messages.values.flatten)

      - # if there's a problem creating the order (this should never happen!), show the order errors, this will help us to debug and the customers to report any unexpected error
      - if @current_cart.order.present? && @current_cart.order.errors.present?
        = error_messages_for(@current_cart.order)

      .row.v-top
        - # shipping address
        .col-12.col-sm-6.p-3
          = render 'frontend/cart/confirm_parts/shipping_address_box', f: f

        - # invoice details
        .col-12.col-sm-6.p-3
          = render 'frontend/cart/confirm_parts/billing_info_box', f: f

      %h3= t('payment_method')

      = link_to cart_show_path, class: 'btn btn-default btn-sm' do
        = t('change_payment_method')

      - payment = @current_cart.payment

      .row
        .payment.p-4.current
          .payment-image
            - if payment.image.present?
              = image_tag(payment.image.url('80x40>'))

          .payment-details
            %h4.mt-0= payment.name
            .details= payment.description_short
          .clearfix

      .row.my-4.v-bottom
        .col-12.col-sm-6.coupon-box.p-4
          - # =f.label :code
          - if @current_cart.coupon.present?
            .row.v-bottom
              .col-8
                = t('coupon_active')
                %h4.text-success.my-0
                  = @current_cart.coupon_code

              .col-4
                %button.btn.btn-danger.btn-block{ type: 'submit', name: 'shopping_cart[coupon_code]', value: '' }
                  = t('remove')

          - else
            .row.v-bottom
              .col-8
                = f.text_field :coupon_code, class: "form-control m-0", placeholder: t('coupon')

              .col-4.pl-0
                %button.btn.btn-default.btn-block{ type: 'submit' }
                  = t('activate')

        .col-12.col-sm-6.mt-4
          %button.btn.btn-success.btn-block.btn-lg{ type: 'submit', name: 'after_update', value: 'make_order', form: 'cart-form' }
            %i.fa.fa-check.mr-2
            = t('finish_order')

app/views/frontend/cart/missing_details.haml
- meta title: t("cart"), description: t("invoice_data")

= cart_panel do
  - if !@current_account.can_order?
    %h2= t 'missing_details.title'
    %p= t 'missing_details.message'

  - else
    %h2= t 'edit_billing_information'
    %p= raw t 'this_data_utilized_for'

  = form_for(@current_account, url: cart_fill_details_path, method: :patch, html: {class: "form floating-labels"}) do |f|
    = error_messages_for(@current_account)

    - # the name and surname are visible only if the account is editing the billing informations
    - if @current_account.can_order?
      -# adds the link to change account typology
      %p
        - if @current_account.vat_customer?
          = t 'customer_registration'
          = link_to t('click_here'), edit_account_path

        - else
          = t 'company_registration'
          = link_to t('click_here'), edit_vat_account_path

        - # name and surname
        = render 'accounts/form_parts/name_surname_fields', form: f, vat_account: @current_account.vat_customer?

    %hr

    - # address fields
    = render 'accounts/form_parts/address_fields', form: f

    - # fiscal code
    = render 'accounts/form_parts/cfis_fields', form: f

    - # additional informations
    = render 'accounts/form_parts/additional_informations_fields', form: f

    %hr

    - # telephone
    = render 'accounts/form_parts/phone_fields', form: f

    .form-group.clearfix.action-buttons
      = link_to :back, t('go_back'), class: 'back-btn'

      = f.submit t('missing_details.submit'), class: 'submit-btn'

app/views/frontend/cart/remove_item.js.erb
(function(){
  // var selector = ".cart-item-<%=@item.id%>";
  // var $item = $(selector);
  // var badge = <%=@current_cart.items.size%>;

  // $item.fadeOut(300, function(){
  //   $item.remove();
  // });

  // $(".cart-quantity-badge").text(badge);

  window.location.reload();
})()

app/views/frontend/cart/show.haml
- meta title: t('cart'), description: t('cart_summary')

= cart_panel do
  %h2.page-title.mb-3= t('cart_summary')

  - if @current_cart.errors.present?
    = error_messages_for(@current_cart)

  - @current_cart.warnings? # this will trigger the warnings callbacks and will populate the warning messages as necessary

  - if @current_cart.warnings.present?
    = flash_warning(@current_cart.warnings.messages.values.flatten)

  - if @items.present?
    = form_for @current_cart, url: cart_update_path, method: :put, remote: true do |f|
      .cart-items
        = f.fields_for :items, @items do |fields|
          - item = fields.object # ShoppingCart::Item instance
          - product = item.product
          - # the cart-item-id is targeted by the remove action javascript that will fadeout that row on success
          .item{ class: "cart-item-#{item.id}" }

            .item-detail
              - # product image
              .item-image.item-box
                - if product.present? && (images = item.product.images).present?
                  = image_tag(images.first.url('128x128#'))

              - # name and description
              .item-details.item-box
                %h4.item-name= item.name

                - if product.present?
                  .item-description
                    %small
                      = strip_tags(item.product.description)

              - # quantity
              .item-quantity.item-box
                - # if the product exists, let the user change the quantity
                - if product.present?
                  .single-price
                    = number_to_currency item.price_with_vat
                    = 'x'

                  .quantity-input
                    = quantity_field_for item.product, item.quantity, "shopping_cart[items_attributes][#{fields.index}][quantity]"

                - else
                  .single-price
                    = number_to_currency item.price_with_vat
                    = 'x'

                  .quantity-input= text_field_tag :quantity, item.quantity

                - # total price
                .item-total{ id: "total-item-price-#{product.id}" }
                  = number_to_currency item.total_with_vat

              -# remove item button
              .item-actions
                -# the delete-cart-item class is needed to let javascript target this link and make a DELETE request
                - message = "#{t('are_you_sure_you_want_to_remove')} #{item.name}?"
                = link_to cart_remove_item_path(item_id: item.id), class: 'delete-cart-item', 'data-message' => message do
                  %i.fa.fa-minus-circle
                  = t('remove')

              .item-actions-mobile
                - message = "#{t('are_you_sure_you_want_to_remove')} #{item.name}?"
                = link_to cart_remove_item_path(item_id: item.id), class: 'delete-cart-item', 'data-message' => message do
                  %i.fa.fa-minus-circle

            - # warning messages
            - # this will trigger the warnings callbacks and will populate the warning messages as necessary
            - item.warnings?

            - if item.warnings.present?
              .item-warnings
                = flash_message('warning', '', item.warnings.messages.values.flatten, false)

            - if item.errors.present?
              .item-errors
                = flash_message('error', '', item.errors.messages.values.flatten, false)

          - content_for :javascripts do
            :javascript
              var $form = $('.edit_shopping_cart')

              $(window).load(function() {
                countPrice("#{product.id}")
              })

              $("#quantity-#{product.id}").change(function() {
                countPrice("#{product.id}")
                $(this).closest('form').submit()
              })


              // remove cart items
              $(".delete-cart-item").click(function(e){
                e.preventDefault();
                var url = $(this).attr("href");
                var message = $(this).attr("data-message");
                message = message === undefined ? "Remove this item from the cart?" : message;


                // if sweet alert has been loaded, use it to display the confirm dialog
                if ( typeof(swal) !== 'undefined' ) {
                  swal({
                    title: '',
                    text: message,
                    showCancelButton: true
                  }).then(function () {
                    ajaxDelete(url)
                  }).catch(swal.noop)
                } else {
                  // fallback without the sweet alert plugin
                  if (confirm(message))
                    ajaxDelete(url)
                }
              })

              function ajaxDelete(url) {
                $.ajax({
                  url: url,
                  method: 'DELETE',
                  dataType: 'script'
                })
              }

        .total-recap-left
          = render 'frontend/cart/parts/total_recap'

      %hr.line-cart

      - if @add_on_products
        .add-ons
          %ul
            - @add_on_products.each do |add_on|
              %li
                .check-box
                  %label
                    .add-on-input= f.check_box :add_on_id, class: 'add-on-checkbox', 'data-id' => add_on.permalink

                    .add-on-details
                      - if add_on.images.logos.present?
                        .add-on-image
                          = image_tag(add_on.images.logos.first.url('48x48#'), class: 'img-fluid')

                      .details
                        %h5
                          = add_on.name
                          - if add_on.price > 0.00
                            %small= "(#{number_to_currency(add_on.price)})"

                        = add_on.description_short

        - content_for :javascripts do
          :javascript
            $('.add-on-checkbox').on('change', function() {
              if (this.checked) {
                var id = $(this).data('id')
                var url = "/it/cart/add_product/" + id
                $.post(url, { quantity: 1, redirect_url: '' }, function() { location.reload() })
              } else {
                alert('unchecked')
              }
            })

      %h2= t('payment_method')

      = render 'frontend/cart/parts/payment_method', f: f

      .form-group.clearfix.action-buttons
        %button.submit-btn{ type: 'submit', name: 'after_update', value: 'account' }
          %i.fa.fa-shopping-basket
          = t('go_to_checkout')

  - else
    = t('no_products_in_cart')

  - content_for :javascripts do
    :javascript
      function countPrice(product_id) {
        $.ajax({
          url: "#{price_calc_products_path}",
          data: {
            product_id: product_id,
            quantity: $('#quantity-' + product_id).val()
          }
        })
      }

app/views/frontend/cart/update.js.erb
<% if params[:after_update] == 'account' %>
  <% if @success %>
    window.location.replace('<%= j cart_registrations_login_or_register_path %>')
  <% end %>
<% else %>
  $('.right-products').html("<%= j render('frontend/cart/parts/items_list') %><hr><%= j render('frontend/cart/parts/total_recap') %>")
<% end %>