config/routes.rb
#
Rails.application.routes.draw do
  # redirects to the appropriate lang
  get '', to: 'frontend#redirect_lang'

  # Start localized routes
  scope '/:locale', locale: /#{Ecommerce.find(ENV['ECOMMERCE_ID']).locales.join('|')}/ do
    # devise
    devise_for :accounts, skip: :registrations, controllers: {
      sessions: 'accounts/sessions',
      passwords: 'accounts/passwords'
    }, path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'password'
      # , confirmation: 'verification',
      # registration: 'register', edit: 'edit'
    }
    devise_scope :account do
      # devise registration
      resource :account_registration, only: [:new], path: "accounts", path_names: {new: "register"}, controller: 'accounts/registrations'
      post "/accounts", controller: "accounts/registrations", action: :create_base, as: :account_registration
      get "/accounts/register/sign_up_vat", controller: "accounts/registrations", action: :new_vat, as: :new_vat_account_registration
      post "/accounts/register_vat", controller: "accounts/registrations", action: :create_vat, as: :vat_account_registration

      resource :account, only: [:edit, :update] do
        get :edit_vat
        get :edit_password
        match :update_vat, via: [:put, :patch]
        match :update_password, via: [:put, :patch]
      end
      # get "/accounts/edit", controller: "accounts", action: :edit, as: :edit_account
      # match "/accounts", controller: "accounts", action: :update, as: :account, via: [:put, :patch]
    end

    # additional devise custom routes
    # namespace :accounts, as: "account", module: nil do
    #   namespace :register, as: "registration", module: "accounts/registrations" do
    #     # get "/accounts/register/sign_up_vat", action: :new_vat, as: :new_vat_account_registration
    #     resource :billing_address, only: [:new, :edit, :update]
    #   end
    # end

    # end devise


    namespace :accounts do
      get :dashboard

      resources :orders, only: [:index, :show] do
        member do
          match :cancel, via: [:put, :patch]
          get :payment
          post :payment, action: :update_payment, as: "update_payment"
        end
      end

      resources :shipping_addresses, except: [:show] do
        match :set_as_default, on: :member, via: [:patch, :put]
      end
    end


    scope module: 'frontend' do
      root to: 'pages#index'
      resources :pages, only: [:show]

      resources :categories, only: [:index, :show]
      resources :products, only: [:show] do
        collection do
          get :price_calc
        end
      end

      # cities and provinces routes
      namespace :addresses do
        # get ":country_id/provinces", action: "provinces", as: :provinces
        get ":province_name/cities", action: "cities", as: :cities
        get ":province_name/:city_name/suggest-cap", action: "suggest_cap", as: :suggest_cap
      end

      namespace :cart do
        root action: :show, as: :show
        post 'add_product/:product_id', action: :add_product, as: :add_product
        delete 'remove_item/:item_id', action: :remove_item, as: :remove_item
        # adds more products via get url
        get 'add_products/:product_ids', action: :add_products_from_url, as: :add_products
        # updates the cart quantities and starts the checkout process
        match '', action: :update, as: :update, via: [:patch, :put]

        # devise registraion and login from the cart
        devise_scope :account do
          namespace :sessions do
            post :create
          end
          namespace :registrations do
            get  :login_or_register
            get  :login_or_register_vat
            post :create_customer
            post :create_vat_account
          end
        end

        # ship address
        get :missing_details
        match :fill_details, via: [:put, :patch]

        get :change_shipping
        post :update_shipping

        get :confirm
        match :make_order, via: [:get, :post]  # final update action that will update the shipping/payment or generate the order
                                               # the GET method is mapped too to correctly intercept the "go back" buttons, a GET request shoul be redirected to the :confirm action
      end

      # path for posting contact forms
      namespace :contacts do
        # post :standard
        post :dynamic, :newsletter
      end

      scope module: "payments" do
        # /en/paga/81/ORD-4973/91.21
        get "paga/:payment_id/:custom_id/:total", action: :external_payment, constraints: {total: /\d+\.\d{2}/}
      end

    end

    # localized error pages
    get '*path', to: 'exceptions#not_found'
  end
  # end localized routes


  # non localized error pages
  get '*path', to: 'exceptions#not_found'
  # Rails expects the error pages to be served from /<error code>.
  match '400', to: 'exceptions#not_found', via: :all
  # error 500 is managed by the file in the public folder, a server error should render a static page!

end

app/controllers/accounts/orders_controller.rb
class Accounts::OrdersController < AccountsController

  add_breadcrumb I18n.t("order_list"), :accounts_orders_path
        

  def index
    # show all account's orders, even if they have been cancelled
    @orders = @current_account.orders.order({created_at: :desc})
    @account_action = "orders"
  end


  def show
    # show all account's orders, even if they have been cancelled
    @order = @current_account.orders.find( params[:id] )
    @account_action = "orders"
    add_breadcrumb "#{t('order_number')} #{@order.custom_id}"
  end


  def cancel
    # only the current_account's active orders can be cancelled
    @order = @current_account.orders.active.find( params[:id] )
    @order.update(cancel_params)
    redirect_to accounts_order_path(@order)
  end



  def payment
    # only the current_account's active orders can be paid
    @order = @current_account.orders.active.find( params[:id] )
    @account_action = "orders"
    @payments = @current_ecommerce.payments.publics.ordered
    add_breadcrumb "#{t('payment')} #{@order.custom_id}"
  end


  def update_payment
    @order = @current_account.orders.active.find( params[:id] )
    @order.update( params[:order].permit(:payment_id) )
    redirect_to action: "payment"
  end



  private

    def cancel_params
      params.require(:order).permit(:reason, :status_note)
    end

end

app/controllers/accounts/passwords_controller.rb
#
class Accounts::PasswordsController < Devise::PasswordsController
  add_breadcrumb I18n.t('retrieve_password')

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  def update
    # devise doesn't check if the password is blank...
    return redirect_to :back if resource_params[:password].blank?
    super
  end

  protected

  #
  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/accounts/registrations_controller.rb
#
class Accounts::RegistrationsController < Devise::RegistrationsController
  include AccountRegistrable
  add_breadcrumb I18n.t('register')

  # this action adds additional custom parameter and then calls the devise's
  # default create
  def create_base
    @additional_resource_params = {
      role: 'basic_user',
      ecommerce_id: @current_ecommerce.id,
      parent_id: EcommerceConfig.store_id
    }
    @failure_view = 'new'
    configure_permitted_parameters
    create_account
  end

  # #
  # def new_vat
  #   build_resource({})
  #   yield resource if block_given?
  #   respond_with resource
  # end

  # #
  # def create_vat
  #   @additional_resource_params = {
  #     role: 'vat_customer',
  #     ecommerce_id: @current_ecommerce.id,
  #     parent_id: EcommerceConfig.store_id
  #   }
  #   @failure_view = 'new_vat'
  #   configure_permitted_parameters
  #   create_account
  # end
end

app/controllers/accounts/sessions_controller.rb
#
class Accounts::SessionsController < Devise::SessionsController
  add_breadcrumb I18n.t('login')
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    # overrides the message with the now options if the request is javascript,
    # to prevent a peristent logout message
    set_flash_message! :notice, :signed_out, { now: true } if signed_out
    yield if block_given?
    respond_to_on_destroy
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    accounts_dashboard_path
  end
end

app/controllers/accounts/shipping_addresses_controller.rb
#
class Accounts::ShippingAddressesController < AccountsController
  before_action :set_account_action
  add_breadcrumb I18n.t('shipping_addresses'), :accounts_shipping_addresses_path

  #
  def index
    @addresses = @current_account.shipping_addresses
  end

  #
  def new
    add_breadcrumb t('new_shipping_address')
    @address = @current_account.shipping_addresses.new
    render 'form'
  end

  #
  def create
    @address = @current_account.shipping_addresses.new(address_params)
    if @address.save
      flash[:shipping_address_success] = t('shipping_address_saved')
      redirect_to edit_accounts_shipping_address_path(id: @address)
    else
      add_breadcrumb t('new_shipping_address')
      render 'form'
    end
  end

  #
  def edit
    @address = @current_account.shipping_addresses.find(params[:id])
    add_breadcrumb t('edit_shipping_address'), edit_accounts_shipping_address_path(id: @address)
    render 'form'
  end

  #
  def update
    @address = @current_account.shipping_addresses.find(params[:id])
    flash.now[:shipping_address_success] = t('shipping_address_saved') if @address.update(address_params)

    render 'form'
  end

  #
  def set_as_default
    @address = @current_account.shipping_addresses.find(params[:id])
    @address.set_as_default!

    redirect_to action: :index
  end

  #
  def destroy
    @address = @current_account.shipping_addresses.find(params[:id])
    @address.destroy
    redirect_to action: :index
  end

  private

  #
  def set_account_action
    @account_action = 'shipping_addresses'
  end

  #
  def address_params
    params.require(:shipping_address).permit(
      %i[name address address_2 country province city cap telephone note
         telephone_prefix]
    )
  end
end

app/controllers/accounts_controller.rb
#
class AccountsController < FrontendController
  before_action :authenticate_account!, :load_account_vars
  add_breadcrumb I18n.t('home'), :root_path
  add_breadcrumb I18n.t('my_account'), :accounts_dashboard_path

  #
  def dashboard
    @account_action = 'dashboard'
    @latest_orders = @account_orders.limit(3)
  end

  # basic edit action
  def edit
    add_breadcrumb t('edit_data'), edit_account_path
    @account_action = 'edit'
  end

  # edit a vat account (this is also used to pass the user from a cliente to a
  # vat account)
  def edit_vat
    add_breadcrumb t('edit_data'), edit_vat_account_path
    @account_action = 'edit'
  end

  #
  def update
    @account_action = 'edit'
    @current_account.role = 'cliente'
    flash.now[:account_success] = t('account_saved') if @current_account.update(account_permitted_params)

    render 'edit'
  end

  #
  def update_vat
    @account_action = 'edit'
    @current_account.role = 'vat_customer'
    flash.now[:account_success] = t('account_saved') if @current_account.update(account_permitted_params)

    render 'edit_vat'
  end

  #
  def edit_password
    add_breadcrumb t('change_password'), edit_password_account_path
    @account_action = 'edit_password'
  end

  #
  def update_password
    @account_action = 'edit_password'

    if @current_account.update_with_password(account_password_permitted_params)
      # if the account password is updated, the user is automatically logged out
      # and the edit action won't be reached but if the password passed is
      # blank, the account won't be updated and he will see the edit form again
      return redirect_to edit_password_account_path
    end

    render 'edit_password'
  end

  private

  #
  def load_account_vars
    # load the orders made by the current account on the ecommerces managed by
    # this application
    @account_orders = @current_account.orders.order(created_at: :desc)
  end

  #
  def account_permitted_params
    if @current_account.vat_customer?
      params.require(:account).permit(
        %i[name surname corporate_name piva cfis telephone_prefix telephone
           phone_prefix phone address address_2 country province city cap]
      )
    else
      params.require(:account).permit(
        %i[name surname cfis address address_2 country province city cap
           telephone phone telephone_prefix phone_prefix birthday sex]
      )
    end
  end

  #
  def account_password_permitted_params
    params.require(:account).permit(%i[password password_confirmation current_password])
  end
end

app/views/accounts/dashboard.haml
- meta title: t('dashboard'), description: t('dashboard')

= account_panel do
  - if !@current_account.can_order?
    .alert.alert-info.alert-dismissable{ role: 'alert' }
      = raw t('need_invoice_details', link: edit_account_path)

  - # unpaid orders reminder
  = render 'accounts/shared/unpaid_orders'

  %h3= t('latest_orders')

  = render 'accounts/shared/orders_table', orders: @latest_orders

app/views/accounts/edit.haml
- meta title: t('edit_your_account'), description: t('edit_your_account')

= account_panel do
  %h3= t('edit_your_account')

  = form_for @current_account, url: account_path, html: { class: 'form floating-labels' } do |f|
    = error_messages_for(@current_account)

    - if flash[:account_success].present?
      = flash_success(flash[:account_success])

    - # name and surname
    = render 'accounts/form_parts/name_surname_fields', form: f, vat_account: @current_account.vat_customer?

    %hr
    - # address fields
    %h4= t('invoice_data')
    = render 'accounts/form_parts/address_fields', form: f

    - # fiscal code
    = render 'accounts/form_parts/cfis_fields', form: f

    - # telephone
    = render 'accounts/form_parts/phone_fields', form: f

    %hr

    %h4= t('additional_informations')
    - # additional informations
    = render 'accounts/form_parts/additional_informations_fields', form: f

    .form-group
      = f.submit t('save_changes'), class: 'submit-btn'

  %p
    = t('company_registration')
    = link_to edit_vat_account_path do
      = t('click_here')

app/views/accounts/edit_password.haml
- meta title: t('edit_your_account'), description: t('edit_your_account')

= account_panel do
  %h3= t('change_password')

  = form_for @current_account, url: update_password_account_path, html: { class: 'form floating-labels' } do |form|
    = error_messages_for(@current_account)

    .email-pw
      %h4= t('current_password')

      .form-row
        .form-group.col-12.col-md-6
          = form.password_field :current_password, autocomplete: 'off', class: 'form-control', placeholder: true

      %hr

      %h4= t('new_password')

      .form-row
        .form-group.col-12.col-md-6
          = form.password_field :password, autocomplete: 'off', class: 'form-control', placeholder: true

          - if @minimum_password_length
            %span.help-block
              = t('minimum_password_length', length: @minimum_password_length)

        .form-group.col-12.col-md-6
          = form.password_field :password_confirmation, autocomplete: 'off', class: 'form-control', placeholder: true

      .form-group
        = form.submit t('save_changes'), class: 'submit-btn'

app/views/accounts/edit_vat.haml
-meta title: t("edit_your_account"), description: t("edit_your_account")

=account_panel do
  %h2
    =t("edit_your_account")
  
  =form_for @current_account, url: update_vat_account_path, method: :patch, html: {class: "form floating-labels"} do |f|
    =error_messages_for(@current_account)

    -if flash[:account_success].present?
      =flash_success(flash[:account_success])

    -# general fields
    =render partial: "accounts/form_parts/company_general_fields", locals: {form: f}

    -# telephone
    =render partial: "accounts/form_parts/phone_fields", locals: {form: f}
    %hr

    -# address fields
    =render partial: "accounts/form_parts/address_fields", locals: {form: f}

    %hr
    -# legal rapresentant data
    =render partial: "accounts/form_parts/name_surname_fields", locals: {form: f, vat_account: true}


    .form-group
      = f.submit t("save_changes"), class: "btn btn-primary"

  %p
    =t("customer_registration")
    =link_to edit_account_path do
      =t("click_here")

app/views/accounts/faq.haml
-meta title: t("faq_page.title"), description: t("faq_page.title")

=account_panel do
  .faq-page
    -t("faq_page.questions").each_pair do |k, values|
      -title = values[:title]
      -message = values[:message]

    
      .question-box
        .question.p-4>
          %i.fa.fa-question-circle.faq-icon>
          %h4>
            =title

        .answer.p-4.bg-info
          %i.fa.fa-info.faq-icon
          .message
            =message